//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigNumberSum.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertNumbers", ReplyAction="http://tempuri.org/IUserService/InsertNumbersResponse")]
        string InsertNumbers(string number1, string number2, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/InsertNumbers", ReplyAction="http://tempuri.org/IUserService/InsertNumbersResponse")]
        System.Threading.Tasks.Task<string> InsertNumbersAsync(string number1, string number2, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllNumberInfos", ReplyAction="http://tempuri.org/IUserService/GetAllNumberInfosResponse")]
        string GetAllNumberInfos(System.Nullable<int> userId, System.Nullable<System.DateTime> fromDate, System.Nullable<System.DateTime> toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllNumberInfos", ReplyAction="http://tempuri.org/IUserService/GetAllNumberInfosResponse")]
        System.Threading.Tasks.Task<string> GetAllNumberInfosAsync(System.Nullable<int> userId, System.Nullable<System.DateTime> fromDate, System.Nullable<System.DateTime> toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        string GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<string> GetAllUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : BigNumberSum.ServiceReference1.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<BigNumberSum.ServiceReference1.IUserService>, BigNumberSum.ServiceReference1.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertNumbers(string number1, string number2, string userName) {
            return base.Channel.InsertNumbers(number1, number2, userName);
        }
        
        public System.Threading.Tasks.Task<string> InsertNumbersAsync(string number1, string number2, string userName) {
            return base.Channel.InsertNumbersAsync(number1, number2, userName);
        }
        
        public string GetAllNumberInfos(System.Nullable<int> userId, System.Nullable<System.DateTime> fromDate, System.Nullable<System.DateTime> toDate) {
            return base.Channel.GetAllNumberInfos(userId, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<string> GetAllNumberInfosAsync(System.Nullable<int> userId, System.Nullable<System.DateTime> fromDate, System.Nullable<System.DateTime> toDate) {
            return base.Channel.GetAllNumberInfosAsync(userId, fromDate, toDate);
        }
        
        public string GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<string> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
    }
}
