//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuberInfo
    {
        public int ID { get; set; }
        public string FirstNumber { get; set; }
        public string SecondNumber { get; set; }
        public string SumResult { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CalculationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
